### ISSUE TITLE
My stats - Todays consumption is not working correctly

### ISSUE THREAD

**Issue by andersmoe** [knutesten/frisk2-frontend#6]
Does not show stats only for today. See attached screenshots.

![screen shot 2016-08-16 at 12 00 09](https://cloud.githubusercontent.com/assets/5219957/17695558/682712b4-63a9-11e6-899b-38b2a43a3d5f.png)
![screen shot 2016-08-16 at 12 00 17](https://cloud.githubusercontent.com/assets/5219957/17695559/682863b2-63a9-11e6-9299-6d7fe7a4fa30.png)

**Comment by knutesten** [comment]
I think this might be a backend bug, but will investigate further before closing.
